# Generated by Django 3.2.14 on 2022-11-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20221101_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phn_no',
            field=models.IntegerField(),
        ),
    ]
