# Generated by Django 3.2.14 on 2022-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20221114_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
