# Generated by Django 3.2.14 on 2022-10-14 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dec',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
