# Generated by Django 3.2.14 on 2022-11-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_product_dec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Kids',
        ),
    ]
