# Generated by Django 3.2.15 on 2022-11-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_remove_watchlist_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
